#!/usr/bin/env bash

set -eo pipefail

declare model="${1:-srv/}"
declare myname="$(basename "$0")"
declare HERE
HERE="$(dirname "$0")"

filter() {
  local match="c$"
  if [[ $myname =~ $match ]]; then
    bat \
      --language yaml \
      --paging never \
      --plain
  else
    cat
  fi
}

cds compile --to yaml "$model" \
  | "$HERE/yfmt" \
  | filter
